# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
