# Generated by Django 4.2.30 on 2026-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(choices=[('Feriado', 'Feriado'), ('Examen', 'Examen'), ('Institucional', 'Institucional')], default='Feriado', max_length=50),
        ),
    ]
