# Generated by Django 4.2.30 on 2026-05-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_eventocalendario_tipo_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocalendario',
            name='tipo_evento',
        ),
    ]
