# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('dia_corte_mensual', models.SmallIntegerField(default=20)),
                ('red_wifi_campus', models.CharField(blank=True, max_length=100)),
                ('metodo_validacion_ubicacion', models.CharField(choices=[('gps_o_wifi', 'GPS o WiFi'), ('solo_wifi', 'Solo WiFi'), ('solo_gps', 'Solo GPS')], default='gps_o_wifi', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
