# Generated by Django 6.0.5 on 2026-06-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracion_campus_gps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='dia_corte_mensual',
        ),
    ]
