# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slothorario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slothorario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='slothorario',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materiacarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asociadas', to='academico.carrera'),
        ),
        migrations.AddField(
            model_name='materiacarrera',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materiacarrera',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_asociadas', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='materiacarrera',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrera',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrera',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materiacarrera',
            unique_together={('materia', 'carrera')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('codigo_siu', 'anio')},
        ),
    ]
