# Generated by Django 6.0.5 on 2026-06-03 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slothorario',
            name='valido_desde',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slothorario',
            name='valido_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
