# Generated by Django 6.0.5 on 2026-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_slothorario_valido_desde_slothorario_valido_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='institucion',
            field=models.CharField(choices=[('ices', 'ICES'), ('ucse', 'UCSE')], default='ices', max_length=20),
        ),
    ]
