# Generated by Django 6.0.5 on 2026-07-31 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_carrera_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slothorario',
            name='valido_desde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slothorario',
            name='valido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
