# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('anio', models.SmallIntegerField()),
                ('tipo_clase', models.CharField(choices=[('presencial', 'Presencial'), ('virtual_sincronica', 'Virtual Sincrónica'), ('asincronica', 'Asincrónica')], max_length=30)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_validada', models.BooleanField(blank=True, null=True)),
                ('latitud_registrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_registrada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_registrada', models.GenericIPAddressField(blank=True, null=True)),
                ('nota', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('nota_docente', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('nota_secretaria', models.TextField(blank=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
