# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudemergencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudemergencia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='solicitudemergencia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudemergencia',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.secretario'),
        ),
        migrations.AddField(
            model_name='solicitudemergencia',
            name='slot_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.slothorario'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='slot_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.slothorario'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='solicitud_emergencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.solicitudemergencia'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('docente', 'slot_horario', 'fecha')},
        ),
    ]
