"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from corsheaders.defaults import default_headers


def _get_bool_env(name: str, default: str = 'False') -> bool:
    return os.getenv(name, default).strip().lower() == 'true'


def _get_csv_env(name: str, default: str = '') -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env('DEBUG')  # Cambiar a False en producción
ALLOWED_HOSTS = _get_csv_env('ALLOWED_HOSTS')  # En producción especificar dominios
CORS_ALLOW_ALL_ORIGINS = _get_bool_env('CORS_ALLOW_ALL_ORIGINS')
CORS_ALLOWED_ORIGINS = _get_csv_env('CORS_ALLOWED_ORIGINS')  # URL del frontend

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-skip-toast',
]

# --- CONFIGURACIÓN DE SESIONES Y COOKIES ---
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'
# 1. Duración de la sesión (ej. 6 meses en segundos)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 180  

# 2. Renovar la cookie cada vez que interactúan con la API (mantiene la sesión viva)
SESSION_SAVE_EVERY_REQUEST = True 

# 3. Seguridad exigida en RNF-06
SESSION_COOKIE_HTTPONLY = True # Javascript (React) NO puede leer la cookie

# 4. Asegurarse de que el frontend (React) envíe las credenciales en peticiones CORS
CORS_ALLOW_CREDENTIALS = True 
CSRF_COOKIE_HTTPONLY = False   # Debe ser False para que Axios pueda leerlo y mandarlo en el header



SESSION_COOKIE_SECURE = _get_bool_env('SESSION_COOKIE_SECURE')  # En producción, cambiar a True para que solo se envíe por HTTPS
CSRF_COOKIE_SECURE = _get_bool_env('CSRF_COOKIE_SECURE')     # En producción, cambiar a True para que solo se
SECURE_SSL_REDIRECT = _get_bool_env('SECURE_SSL_REDIRECT')  # En producción, cambiar a True para redirigir HTTP a HTTPS

CSRF_TRUSTED_ORIGINS = _get_csv_env('CSRF_ORIGINS')  # URL del frontend y orígenes de confianza
# Le indicamos a Django que use nuestro Custom User
AUTH_USER_MODEL = 'usuarios.Usuario'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'academico',
    'asignaciones',
    'asistencia',
    'calendario',
    'configuracion',
    'core',
    'importacion',
    'reportes',
    'usuarios',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get("SUPABASE_DB_HOST"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get("SUPABASE_DB_NAME", "postgres"),
            'USER': os.environ.get("SUPABASE_DB_USER"),
            'PASSWORD': os.environ.get("SUPABASE_DB_PASSWORD"),
            'HOST': os.environ.get("SUPABASE_DB_HOST"),
            'PORT': os.environ.get("SUPABASE_DB_PORT", "6543"),
            
            # Opcional pero recomendado para Supabase:
            # Mantiene la conexión abierta 10 minutos para que el backend responda más rápido
            'CONN_MAX_AGE': 600, 
        }
    }
else:
    # Si no están las variables de Supabase, usamos tu base local
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('NAME'),
        'USER': os.getenv('USER'),
        'PASSWORD': os.getenv('PASSWORD'),
        'HOST': os.getenv('HOST'),
        'PORT': os.getenv('PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
