# Generated by Django 6.0.5 on 2026-08-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(default='iniciado', max_length=50)),
                ('fase', models.CharField(blank=True, max_length=50)),
                ('paso', models.CharField(blank=True, max_length=255)),
                ('progreso', models.IntegerField(default=0)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('errores', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
