# Generated by Django 4.2.30 on 2026-05-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('academico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado', to=settings.AUTH_USER_MODEL),
        ),
    ]
